# Generated by Django 3.1 on 2021-01-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="deal", name="expired_on", field=models.DateTimeField(null=True),),
        migrations.AddField(model_name="deal", name="price_history", field=models.JSONField(default=list),),
    ]
