# Generated by Django 3.1 on 2021-01-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0002_remove_deal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="img_url",
            field=models.CharField(
                default="https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty.jpg", max_length=255
            ),
        ),
    ]
