# Generated by Django 3.1 on 2021-01-23 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_auto_20210122_0108"),
        ("deal", "0002_auto_20210121_1638"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchList",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="deal.deal")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={"db_table": "bookmarked_deals",},
        ),
    ]
