# Generated by Django 3.1 on 2021-01-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0002_deal_product_keywords"),
    ]

    operations = [
        migrations.AlterField(model_name="deal", name="title", field=models.TextField(),),
        migrations.AlterField(model_name="deal", name="url", field=models.TextField(),),
    ]
