# Generated by Django 3.1 on 2021-01-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0003_bookmarkeddeal"),
    ]

    operations = [
        migrations.AlterModelTable(name="watchlist", table="watch_list",),
    ]
