# Generated by Django 3.1 on 2021-01-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_auto_20210116_2108"),
        ("deal", "0004_bookmark"),
    ]

    operations = [
        migrations.RenameModel(old_name="Bookmark", new_name="WatchList",),
        migrations.AlterModelTable(name="watchlist", table="watchlists",),
    ]
