# Generated by Django 3.1 on 2021-01-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0004_auto_20210123_2137"),
    ]

    operations = [
        migrations.AlterModelTable(name="watchlist", table="watch_lists",),
    ]
