# Generated by Django 3.1 on 2021-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0005_auto_20210105_0351"),
    ]

    operations = [
        migrations.AddField(model_name="deal", name="all_img_urls", field=models.JSONField(default=dict),),
    ]
