# Generated by Django 3.1 on 2021-01-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0005_auto_20210118_2125"),
    ]

    operations = [
        migrations.AddField(model_name="deal", name="category", field=models.JSONField(default=list),),
    ]
