# Generated by Django 3.1 on 2021-01-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0006_deal_category"),
    ]

    operations = [
        migrations.DeleteModel(name="WatchList",),
    ]
