# Generated by Django 3.1 on 2021-01-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0007_delete_watchlist"),
    ]

    operations = [
        migrations.AddField(model_name="userdeal", name="is_on_watchlist", field=models.IntegerField(default=0),),
    ]
