# Generated by Django 3.1 on 2021-01-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0008_followedbrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="img_url",
            field=models.CharField(
                default="https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty.jpg", max_length=255
            ),
        ),
    ]
