# Generated by Django 3.1 on 2021-02-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_user_name"),
        ("deal", "0009_brand_img_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="followedbrand", unique_together={("brand_id", "user_id")},),
    ]
