# Generated by Django 3.1 on 2021-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0011_auto_20210203_0107"),
    ]

    operations = [
        migrations.RemoveField(model_name="matcheddeal", name="is_on_watchlist",),
        migrations.AlterField(model_name="deal", name="uid", field=models.CharField(max_length=255, unique=True),),
    ]
