# Generated by Django 3.1 on 2021-02-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0013_brand_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand", name="color_code", field=models.CharField(default="#000", max_length=255),
        ),
    ]
