# Generated by Django 3.1 on 2021-02-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0014_brand_color_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="brand",
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to="deal.brand"),
            preserve_default=False,
        ),
    ]
