# Generated by Django 3.1 on 2021-02-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0015_deal_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='html',
            field=models.BinaryField(default=b'default'),
            preserve_default=False,
        ),
    ]
