# Generated by Django 3.1 on 2020-12-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid_local", "0002_auto_20201205_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="access_token",
            field=models.CharField(default="XXX", max_length=255),
            preserve_default=False,
        ),
    ]
