# Generated by Django 3.1 on 2020-12-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid_local", "0003_link_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="item_id",
            field=models.CharField(default="XXX", max_length=255),
            preserve_default=False,
        ),
    ]
