# Generated by Django 3.1 on 2020-12-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("plaid_local", "0004_link_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="user",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="user.user"),
            preserve_default=False,
        ),
    ]
