# Generated by Django 3.1 on 2020-12-05 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("plaid_local", "0005_link_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("did_complete", models.IntegerField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={"db_table": "transaction_tasks",},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("amount", models.FloatField()),
                ("account_id", models.CharField(max_length=255)),
                ("category", models.JSONField()),
                ("date", models.DateTimeField()),
                ("location", models.JSONField(default=dict)),
                ("merchant_name", models.CharField(max_length=255)),
                ("payment_channel", models.CharField(max_length=255)),
                ("payment_meta", models.JSONField(default=dict)),
                ("pending", models.IntegerField()),
                ("transaction_id", models.CharField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={"db_table": "transactions",},
        ),
    ]
