# Generated by Django 3.1 on 2020-12-28 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plaid_local', '0006_transaction_transactiontask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plaid_local.link')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
