# Generated by Django 3.1 on 2020-12-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid_local", "0008_delete_account"),
    ]

    operations = [
        migrations.AddField(model_name="link", name="active", field=models.IntegerField(default=1),),
    ]
