# Generated by Django 3.1 on 2021-01-05 01:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0015_auto_20210103_0046"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("discount", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("img_url", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("uid", models.CharField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={"db_table": "deals",},
        ),
    ]
