# Generated by Django 3.1 on 2021-01-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_auto_20210103_0046"),
        ("deals", "0003_auto_20210105_0328"),
    ]

    operations = [
        migrations.AddField(model_name="deal", name="user", field=models.ManyToManyField(to="user.User"),),
    ]
