# Generated by Django 3.1 on 2021-01-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0006_deal_all_img_urls"),
    ]

    operations = [
        migrations.RenameField(model_name="deal", old_name="discount", new_name="current_value",),
        migrations.RenameField(model_name="deal", old_name="value", new_name="original_value",),
    ]
