# Generated by Django 3.1 on 2021-01-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0007_auto_20210110_0104"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="scraper",
            field=models.CharField(default="target", max_length=255),
            preserve_default=False,
        ),
    ]
