# Generated by Django 3.1 on 2020-12-06 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_login_notification"),
    ]

    operations = [
        migrations.AlterField(model_name="notification", name="seen", field=models.IntegerField(default=0),),
    ]
