# Generated by Django 3.1 on 2020-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20201206_0002"),
    ]

    operations = [
        migrations.AlterField(model_name="notification", name="expiry", field=models.DateTimeField(),),
    ]
