# Generated by Django 3.1 on 2020-12-28 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20201206_0005"),
    ]

    operations = [
        migrations.AddField(model_name="login", name="user_agent", field=models.CharField(max_length=255, null=True),),
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "metadata",
                    models.JSONField(default={"profile_sharing_enabled": True, "targeted_advertising_enabled": True}),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.user")),
            ],
            options={"db_table": "settings",},
        ),
    ]
