# Generated by Django 3.1 on 2020-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_auto_20201228_2038"),
    ]

    operations = [
        migrations.AlterField(model_name="setting", name="metadata", field=models.JSONField(default=dict),),
    ]
