# Generated by Django 3.1 on 2020-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_auto_20201230_2129"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="seen",),
        migrations.AddField(model_name="notification", name="seen_at", field=models.DateTimeField(null=True),),
    ]
