# Generated by Django 3.1 on 2020-12-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20201230_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification", name="route_key", field=models.CharField(max_length=255, null=True),
        ),
    ]
