# Generated by Django 3.1 on 2020-12-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_notification_route_key"),
    ]

    operations = [
        migrations.AddField(model_name="notification", name="metadata", field=models.JSONField(default=dict),),
    ]
