# Generated by Django 3.1 on 2021-01-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_profile"),
    ]

    operations = [
        migrations.AlterModelTable(name="profile", table="profiles",),
    ]
