# Generated by Django 3.1 on 2021-01-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_auto_20210103_0005"),
    ]

    operations = [
        migrations.AddField(model_name="profile", name="targeting_enabled", field=models.IntegerField(default=1),),
    ]
