# Generated by Django 3.1 on 2021-01-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_profile_targeting_enabled"),
    ]

    operations = [
        migrations.RenameField(model_name="setting", old_name="metadata", new_name="keywords",),
        migrations.DeleteModel(name="Profile",),
    ]
