# Generated by Django 3.1 on 2021-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_auto_20210103_0046"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification", name="title", field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
