# Generated by Django 3.1 on 2021-01-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_notification_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="address_line1",),
        migrations.RemoveField(model_name="user", name="address_line2",),
        migrations.RemoveField(model_name="user", name="user_meta",),
        migrations.RemoveField(model_name="user", name="user_type",),
    ]
