# Generated by Django 3.1 on 2021-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_auto_20210110_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="current_websocket_addr", field=models.CharField(max_length=255, null=True),
        ),
    ]
