# Generated by Django 3.1 on 2021-01-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_user_current_websocket_addr"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="current_websocket_addr",),
    ]
