# Generated by Django 3.1 on 2021-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_remove_user_current_websocket_addr"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="name",),
        migrations.RemoveField(model_name="user", name="username",),
        migrations.AlterField(
            model_name="user", name="phone", field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
