# Generated by Django 3.1 on 2021-01-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_user_invitation_code"),
    ]

    operations = [
        migrations.AlterField(model_name="user", name="email", field=models.CharField(max_length=255),),
    ]
