# Generated by Django 3.1 on 2021-01-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_auto_20210129_0211"),
    ]

    operations = [
        migrations.AddField(model_name="user", name="name", field=models.CharField(max_length=255, null=True),),
    ]
