export default {
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_CURRENT_SCENE_KEY: 'SET_CURRENT_SCENE_KEY',

  TOGGLE_BROKER_PRODUCT_DETAILS_MODAL: 'TOGGLE_BROKER_PRODUCT_DETAILS_MODAL',

  PRODUCT_INFO_LIKE: 'PRODUCT_INFO_LIKE',

  SET_FEEDBACK_TOPIC: 'SET_FEEDBACK_TOPIC',
  UNSET_FEEDBACK_TOPIC: 'UNSET_FEEDBACK_TOPIC',

  LIKE_CURRENT_PRODUCT: 'LIKE_CURRENT_PRODUCT',
  UNLIKE_CURRENT_PRODUCT: 'UNLIKE_CURRENT_PRODUCT',

  UPDATE_CURRENT_MESSAGE_TEXT: 'UPDATE_CURRENT_MESSAGE_TEXT',

  POST_USER_LOGIN: 'POST_USER_LOGIN',
  CLEAR_POST_LOGIN_ERROR: 'CLEAR_POST_LOGIN_ERROR',
  POST_USER_LOGIN_SUCCESS: 'POST_USER_LOGIN_SUCCESS',
  POST_USER_LOGIN_PENDING: 'POST_USER_LOGIN_PENDING',
  POST_USER_LOGIN_ERROR: 'POST_USER_LOGIN_ERROR',
  UPDATE_LOGIN_EMAIL: 'UPDATE_LOGIN_EMAIL',
  UPDATE_LOGIN_PASSWORD: 'UPDATE_LOGIN_PASSWORD',

  INVALID_LOGIN_EMAIL_VALUE: 'INVALID_LOGIN_EMAIL_VALUE',
  INVALID_LOGIN_PASSWORD_VALUE: 'INVALID_LOGIN_PASSWORD_VALUE',

  GET_NOTIFICATIONS_PENDING: 'GET_NOTIFICATIONS_PENDING',
  GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',

  GET_MESSAGES_PENDING: 'GET_MESSAGES_PENDING',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',
  CLEAR_GET_MESSAGES_ERROR: 'CLEAR_GET_MESSAGES_ERROR',
  POST_MESSAGE_PENDING: 'POST_MESSAGE_PENDING',
  POST_MESSAGE_ERROR: 'POST_MESSAGE_ERROR',
  POST_MESSAGE_SUCCESS: 'POST_MESSAGE_SUCCESS',
  CLEAR_POST_MESSAGE_ERROR: 'CLEAR_POST_MESSAGE_ERROR',
  CLEAR_UNSENT_MESSAGE: 'CLEAR_UNSENT_MESSAGE',

  GET_CONVERSATIONS_PENDING: 'GET_CONVERSATIONS_PENDING',
  GET_CONVERSATIONS_ERROR: 'GET_CONVERSATIONS_ERROR',
  GET_CONVERSATIONS_SUCCESS: 'GET_CONVERSATIONS_SUCCESS',
  CLEAR_GET_CONVERSATIONS_ERROR: 'CLEAR_GET_CONVERSATIONS_ERROR',

  UPDATE_BROKER_BRAND_VIEW_SEARCH_INPUT: 'UPDATE_BROKER_BRAND_VIEW_SEARCH_INPUT',
  CLEAR_BROKER_BRAND_VIEW_SEARCH_INPUT: 'CLEAR_BROKER_BRAND_VIEW_SEARCH_INPUT',
};
