export default {
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_CURRENT_SCENE_KEY: 'SET_CURRENT_SCENE_KEY',

  TOGGLE_BROKER_PRODUCT_DETAILS_MODAL: 'TOGGLE_BROKER_PRODUCT_DETAILS_MODAL',

  PRODUCT_INFO_LIKE: 'PRODUCT_INFO_LIKE',

  SET_FEEDBACK_TOPIC: 'SET_FEEDBACK_TOPIC',
  UNSET_FEEDBACK_TOPIC: 'UNSET_FEEDBACK_TOPIC',

  LIKE_CURRENT_PRODUCT: 'LIKE_CURRENT_PRODUCT',
  UNLIKE_CURRENT_PRODUCT: 'UNLIKE_CURRENT_PRODUCT',
};
