export default {
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_CURRENT_SCENE_KEY: 'SET_CURRENT_SCENE_KEY',

  TOGGLE_BROKER_PRODUCT_DETAILS_MODAL: 'TOGGLE_BROKER_PRODUCT_DETAILS_MODAL',

  PRODUCT_INFO_LIKE: 'PRODUCT_INFO_LIKE',

  SET_FEEDBACK_TOPIC: 'SET_FEEDBACK_TOPIC',
  UNSET_FEEDBACK_TOPIC: 'UNSET_FEEDBACK_TOPIC',

  LIKE_CURRENT_PRODUCT: 'LIKE_CURRENT_PRODUCT',
  UNLIKE_CURRENT_PRODUCT: 'UNLIKE_CURRENT_PRODUCT',

  UPDATE_CURRENT_MESSAGE_TEXT: 'UPDATE_CURRENT_MESSAGE_TEXT',

  POST_USER_LOGIN: 'POST_USER_LOGIN',
  CLEAR_POST_LOGIN_ERROR: 'CLEAR_POST_LOGIN_ERROR',
  POST_USER_LOGIN_SUCCESS: 'POST_USER_LOGIN_SUCCESS',
  POST_USER_LOGIN_PENDING: 'POST_USER_LOGIN_PENDING',
  POST_USER_LOGIN_ERROR: 'POST_USER_LOGIN_ERROR',
  UPDATE_LOGIN_EMAIL: 'UPDATE_LOGIN_EMAIL',
  UPDATE_LOGIN_PASSWORD: 'UPDATE_LOGIN_PASSWORD',

  INVALID_LOGIN_EMAIL_VALUE: 'INVALID_LOGIN_EMAIL_VALUE',
  INVALID_LOGIN_PASSWORD_VALUE: 'INVALID_LOGIN_PASSWORD_VALUE',

  GET_NOTIFICATIONS_PENDING: 'GET_NOTIFICATIONS_PENDING',
  GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
};
