# Generated by Django 3.1 on 2020-08-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
