# Generated by Django 3.1 on 2020-08-16 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_auto_20200808_2257"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True),),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("email", models.CharField(max_length=255, primary_key=True, serialize=False),),
            ],
            options={"db_table": "interests",},
        ),
    ]
