# Generated by Django 3.1 on 2020-09-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_interest"),
    ]

    operations = [
        migrations.AlterField(model_name="user", name="user_meta", field=models.JSONField(default=dict),),
    ]
