# Generated by Django 3.1 on 2020-09-27 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20200917_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('expiry', models.DateTimeField()),
                ('additional_comments', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.offer')),
            ],
            options={
                'db_table': 'grabs',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('carrier', models.IntegerField()),
                ('tracking_number', models.CharField(max_length=255)),
                ('expected_delivery', models.DateTimeField()),
                ('grab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.grab')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='match',
            name='offer',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='item_route_key',
            new_name='_item_route_key',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='item_route_meta',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='notification',
            name='_item_route_key',
            field=models.CharField(db_column='item_route_key', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='partners.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
