# Generated by Django 3.1 on 2021-01-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scraperstats",
            name="name",
            field=models.CharField(default="https://target.com", max_length=255),
            preserve_default=False,
        ),
    ]
