# Generated by Django 3.1 on 2020-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_reward_merchant"),
    ]

    operations = [
        migrations.AddField(model_name="reward", name="is_active", field=models.IntegerField(default=0),),
    ]
