# Generated by Django 3.1 on 2020-12-06 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0005_auto_20201206_0012"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("target_user_count", models.JSONField(default=dict)),
                ("target_time_active", models.JSONField(default=dict)),
                ("target_user_match", models.JSONField(default=dict)),
                ("merchant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="merchant.merchant")),
            ],
            options={"db_table": "campaigns",},
        ),
        migrations.AddField(
            model_name="reward",
            name="campaign",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="merchant.campaign"),
            preserve_default=False,
        ),
    ]
