# Generated by Django 3.1 on 2020-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0007_campaign_is_active"),
    ]

    operations = [
        migrations.AddField(model_name="campaign", name="keywords", field=models.JSONField(default=list),),
        migrations.AddField(model_name="merchant", name="industry", field=models.JSONField(default=list),),
        migrations.AddField(model_name="merchant", name="keywords", field=models.JSONField(default=list),),
    ]
