# Generated by Django 3.1 on 2020-12-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0008_auto_20201206_1818"),
    ]

    operations = [
        migrations.RemoveField(model_name="reward", name="merchant",),
    ]
