# Generated by Django 3.1 on 2020-12-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0009_remove_reward_merchant"),
    ]

    operations = [
        migrations.RenameField(model_name="reward", old_name="user", new_name="created_by",),
    ]
