# Generated by Django 3.1 on 2020-12-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0010_auto_20201206_1913"),
    ]

    operations = [
        migrations.AlterField(model_name="campaign", name="is_active", field=models.BooleanField(default=False),),
        migrations.AlterField(model_name="reward", name="is_active", field=models.IntegerField(default=1),),
    ]
