# Generated by Django 3.1 on 2020-12-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0011_auto_20201206_1959"),
    ]

    operations = [
        migrations.AddField(model_name="reward", name="redeemed_at", field=models.DateTimeField(null=True),),
    ]
