# Generated by Django 3.1 on 2020-12-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20201206_0005"),
        ("merchant", "0012_reward_redeemed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="activated_by",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="user.user"),
        ),
        migrations.AddField(model_name="campaign", name="activated_on", field=models.DateTimeField(null=True),),
    ]
