# Generated by Django 3.1 on 2020-12-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0013_auto_20201206_2006"),
    ]

    operations = [
        migrations.RenameField(model_name="campaign", old_name="activated_by", new_name="activated_by_user",),
    ]
