# Generated by Django 3.1 on 2020-12-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20201206_0005"),
        ("merchant", "0014_auto_20201206_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="cancelled_by_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="cancelled_by_user", to="user.user"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by_user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="created_by_user", to="user.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="activated_by_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activated_by_user", to="user.user"
            ),
        ),
    ]
