# Generated by Django 3.1 on 2020-12-07 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20201206_0005"),
        ("merchant", "0015_auto_20201206_2015"),
    ]

    operations = [
        migrations.RemoveField(model_name="campaign", name="is_active",),
        migrations.RemoveField(model_name="reward", name="amount",),
        migrations.RemoveField(model_name="reward", name="created_by",),
        migrations.AddField(model_name="campaign", name="cancelled_on", field=models.DateTimeField(null=True),),
        migrations.AddField(model_name="campaign", name="is_cancelled", field=models.IntegerField(default=0),),
        migrations.AddField(
            model_name="reward",
            name="owner_user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="owner_user", to="user.user"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="created_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="campaign_created_by_user", to="user.user"
            ),
        ),
        migrations.CreateModel(
            name="RewardCode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("code", models.CharField(max_length=255)),
                ("value", models.JSONField(default=dict)),
                ("is_active", models.IntegerField(default=0)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="merchant.campaign")),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewardcode_created_by_user",
                        to="user.user",
                    ),
                ),
            ],
            options={"db_table": "reward_codes",},
        ),
        migrations.AlterField(
            model_name="reward",
            name="code",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="merchant.rewardcode"),
        ),
    ]
