# Generated by Django 3.1 on 2020-12-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0017_merchant_users"),
    ]

    operations = [
        migrations.AddField(model_name="rewardcode", name="description", field=models.TextField(null=True),),
    ]
