# Generated by Django 3.1 on 2020-12-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0019_auto_20201225_2321"),
    ]

    operations = [
        migrations.RemoveField(model_name="reward", name="campaign",),
    ]
