# Generated by Django 3.1 on 2020-12-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0020_remove_reward_campaign"),
    ]

    operations = [
        migrations.RenameField(model_name="reward", old_name="qr_code", new_name="qr_code_url",),
    ]
