# Generated by Django 3.1 on 2020-10-10 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "image_url",
                    models.CharField(
                        default="https://cel.ac/wp-content/uploads/2016/02/placeholder-img-1.jpg", max_length=255
                    ),
                ),
            ],
            options={"db_table": "brands",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("username", models.CharField(max_length=255)),
                ("address_line1", models.CharField(max_length=255, null=True)),
                ("address_line2", models.CharField(max_length=255, null=True)),
                ("phone", models.CharField(max_length=255, null=True)),
                ("secret", models.CharField(max_length=255)),
                ("salt", models.IntegerField()),
                ("session_token_key", models.CharField(max_length=255)),
                ("user_meta", models.JSONField(default=dict)),
                ("type", models.CharField(max_length=255)),
                ("qr_code_url", models.CharField(max_length=255)),
                ("site_url", models.CharField(max_length=255, null=True)),
                (
                    "profile_image_url",
                    models.CharField(
                        default="https://cel.ac/wp-content/uploads/2016/02/placeholder-img-1.jpg", max_length=255
                    ),
                ),
            ],
            options={"db_table": "users", "unique_together": {("salt", "secret")},},
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user")),
            ],
            options={"db_table": "wallets",},
        ),
        migrations.CreateModel(
            name="WalletBrand",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("balance", models.FloatField()),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.brand")),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.wallet")),
            ],
            options={"db_table": "wallet_brands",},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("text", models.CharField(max_length=255)),
                ("seen", models.BooleanField(default=False)),
                ("item_type", models.IntegerField()),
                ("_item_route_key", models.CharField(db_column="item_route_key", max_length=255)),
                ("item", models.JSONField(default=dict)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user")),
            ],
            options={"db_table": "notifications",},
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("ip_address", models.CharField(max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.user")),
            ],
            options={"db_table": "logins",},
        ),
        migrations.CreateModel(
            name="CampaignCode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("code", models.CharField(max_length=255)),
                ("expiry", models.DateTimeField()),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.brand")),
            ],
            options={"db_table": "campaign_codes",},
        ),
    ]
