# Generated by Django 3.1 on 2020-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="qr_code_url",
            field=models.CharField(
                default="https://www.kaspersky.com/content/en-global/images/repository/isc/2020/9910/a-guide-to-qr-codes-and-how-to-scan-qr-codes-2.png",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
