# Generated by Django 3.1 on 2020-10-10 19:24

import random
import hashlib

from django.db import migrations
from faker import Faker


from lib.const import UserType

fake = Faker()


def seed_brands(apps, _):
    User = apps.get_model("core", "User")
    count = 20
    for _ in range(count):
        salt = random.randint(1, 10e5)
        secret = hashlib.sha256(("foo" + str(salt)).encode()).hexdigest()
        _ = User.objects.create(
            email=fake.email(),
            session_token_key="123",
            salt=salt,
            secret=secret,
            name=fake.name(),
            phone=fake.phone_number(),
            type=UserType.BROKER,
            username=fake.first_name_female().lower(),
            qr_code_url="https://storage.googleapis.com/grabbit/broker/e%40gmail.com/qr_code",
            address_line1=fake.address(),
        )

    # add broker superuser
    _ = User.objects.create(
        email="b@gmail.com",
        session_token_key="MASTER",
        salt=0,
        secret=hashlib.sha256(("b" + "0").encode()).hexdigest(),
        name="Ava Machina",
        phone="555-555-5555",
        type=UserType.BROKER,
        username="ava",
        qr_code_url="https://storage.googleapis.com/grabbit/broker/e%40gmail.com/qr_code",
        address_line1="600 S Spring St Apt 1602 Los Angeles CA 90014",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_brands)]
