# Generated by Django 3.1 on 2020-10-04 01:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_qr_code_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "image_url",
                    models.CharField(
                        default="https://www.teamunhcr.org.au/images/empty-profile-image.jpg", max_length=255
                    ),
                ),
            ],
            options={"db_table": "brands",},
        ),
        migrations.CreateModel(
            name="BrandCode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("code", models.CharField(max_length=255)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.brand")),
            ],
            options={"db_table": "brand_codes",},
        ),
        migrations.RemoveField(model_name="conversation", name="person_a",),
        migrations.RemoveField(model_name="conversation", name="person_b",),
        migrations.RemoveField(model_name="grab", name="offer",),
        migrations.RemoveField(model_name="message", name="conversation",),
        migrations.RemoveField(model_name="message", name="recipient",),
        migrations.RemoveField(model_name="message", name="sender",),
        migrations.RemoveField(model_name="offer", name="offeree",),
        migrations.RemoveField(model_name="offer", name="offerer",),
        migrations.RemoveField(model_name="offer", name="product",),
        migrations.RemoveField(model_name="product", name="merchant",),
        migrations.RemoveField(model_name="shipment", name="grab",),
        migrations.DeleteModel(name="AttributionStat",),
        migrations.DeleteModel(name="Conversation",),
        migrations.DeleteModel(name="Grab",),
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="Offer",),
        migrations.DeleteModel(name="Product",),
        migrations.DeleteModel(name="Shipment",),
    ]
