# Generated by Django 3.1 on 2020-10-10 17:15

import string
import random
import datetime as dt

from django.db import migrations
from django.utils import timezone
from faker import Faker


fake = Faker()


def fake_code():
    chars = list(string.ascii_uppercase + string.digits)
    return "".join([random.choice(chars) for _ in range(6)])


def seed_campaign_codes(apps, _):
    code_counts = 20
    Brand = apps.get_model("core", "Brand")

    for brand in Brand.objects.all():
        for _ in range(code_counts):
            CampaignCode = apps.get_model("core", "CampaignCode")
            expiry = timezone.now() + timezone.timedelta(days=7)
            _ = CampaignCode.objects.create(brand=brand, code=fake_code(), expiry=expiry)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_brands"),
    ]

    operations = [migrations.RunPython(seed_campaign_codes)]
