# Generated by Django 3.1 on 2020-10-07 01:12

from django.db import migrations
from faker import Faker

from lib.const import DEFAULT_PROFILE_IMAGE

fake = Faker()


def fill_brand_data(apps, _):
    Brand = apps.get_model("core", "Brand")
    count = 20
    for i in range(count):
        print("creating brand profile %i/count", i)
        _ = Brand.objects.create(
            name=fake.company(), description=fake.sentence(nb_words=30), image_url=DEFAULT_PROFILE_IMAGE
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20201004_0105"),
    ]

    operations = [migrations.RunPython(fill_brand_data)]
