# Generated by Django 3.1 on 2020-10-10 19:12

from django.db import migrations
from faker import Faker

fake = Faker()


def seed_wallet_data(apps, _):
    User = apps.get_model("core", "User")
    Wallet = apps.get_model("core", "Wallet")

    for user in User.objects.all():
        _ = Wallet.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_seed_campaign_codes"),
    ]

    operations = [migrations.RunPython(seed_wallet_data)]
