# Generated by Django 3.1 on 2020-10-10 18:52

import random

from django.db import migrations
from faker import Faker

fake = Faker()


def seed_wallet_brands(apps, _):
    Brand = apps.get_model("core", "Brand")
    Wallet = apps.get_model("core", "Wallet")
    WalletBrand = apps.get_model("core", "WalletBrand")

    brands = Brand.objects.all()

    wallet_brands = 10
    for wallet in Wallet.objects.all():
        brand_ids = set()
        for _ in range(wallet_brands):
            random_brand = random.choice(brands)
            while random_brand.id in brand_ids:
                random_brand = random.choice(brands)

            brand_ids.add(random_brand.id)

            _ = WalletBrand.objects.create(wallet=wallet, brand=random_brand, balance=random.uniform(1.5, 31.5))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_wallets"),
    ]

    operations = [migrations.RunPython(seed_wallet_brands)]
