# Generated by Django 3.1 on 2020-10-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20201007_0120"),
    ]

    operations = [
        migrations.RenameModel(old_name="BrandCode", new_name="CampaignCode",),
    ]
