# Generated by Django 3.1 on 2020-10-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201010_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncode',
            name='expiry',
            field=models.DateTimeField(default='2020-10-03 10:18:43.811394-07'),
            preserve_default=False,
        ),
    ]
