# Generated by Django 3.1 on 2020-10-12 02:24

from django.db import migrations, models


def seed_reward_tiers_on_brands(apps, _):
    Brand = apps.get_model("core", "Brand")
    print("seeding rewarding tiers on brands....")
    for brand in Brand.objects.all():
        reward_tiers = {
            "0": {
                "usd": 5,
                "points": 1_000
            },
            "1": {
                "usd": 10,
                "points": 5_000
            },
            "2": {
                "usd": 25,
                "points": 10_000
            },
            "3": {
                "usd": 50,
                "points": 30_000
            },
            "4": {
                "usd": 100,
                "points": 50_000,
            },
        }

        brand.reward_tiers = reward_tiers
        brand.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_wallet_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncode',
            name='reward_tiers',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(seed_reward_tiers_on_brands)
    ]
