# Generated by Django 3.1 on 2020-10-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_campaigncode_reward_tiers"),
    ]

    operations = [
        migrations.RemoveField(model_name="campaigncode", name="reward_tiers",),
        migrations.AddField(model_name="brand", name="reward_tiers", field=models.JSONField(default=dict),),
    ]
