# Generated by Django 3.1 on 2020-10-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20201012_0225"),
    ]

    operations = [
        migrations.AlterField(model_name="brand", name="reward_tiers", field=models.TextField(null=True),),
    ]
