# Generated by Django 3.1 on 2020-10-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20201012_0231"),
    ]

    operations = [
        migrations.AddField(model_name="brand", name="users", field=models.ManyToManyField(to="core.User"),),
    ]
