# Generated by Django 3.1 on 2020-10-18 00:22
import random

from django.db import migrations


def backfill_user_ids_to_brands(apps, _):
    User = apps.get_model("core", "User")
    Brand = apps.get_model("core", "Brand")

    users = list(User.objects.all())

    for brand in Brand.objects.all():
        brand_users = random.sample(users, random.randint(1, 3))
        for user in brand_users:
            brand.users.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_brand_users"),
    ]

    operations = [migrations.RunPython(backfill_user_ids_to_brands)]
