# Generated by Django 3.1 on 2020-10-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20201019_0001"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="secret",
            field=models.CharField(default="XXX48474204", max_length=255),
            preserve_default=False,
        ),
    ]
