# Generated by Django 3.1 on 2020-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_brand_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=models.CharField(default="default-slug", max_length=255),
            preserve_default=False,
        ),
    ]
