# Generated by Django 3.1 on 2020-10-21 02:08

from django.db import migrations
from core.models import Brand


def backfill_brand_slugs(*_):
    for brand in Brand.objects.all():
        brand.set_slug()
        brand.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_brand_slug"),
    ]

    operations = [migrations.RunPython(backfill_brand_slugs)]
