version: "3"
volumes:
  postgresdata:
services:
  grabbit:
    build: .
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        ./scripts/pgwait.sh postgresql
        make start_prod
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/grabbit
    env_file:
      - .env.prod
    depends_on:
      - redis
      - postgresql
  postgresql:
    image: postgres:12.2
    restart: always
    ports:
      - 5432
    volumes:
      - ./scripts/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grabbit_prod
      POSTGRES_USER: postgres
  redis:
    restart: always
    image: redis:5.0
    ports:
      - 6379
  redis-cli:
    depends_on:
        - redis
    image: redis:5.0
    command: redis-cli -h redis ping